### ISSUE TITLE
Ошибка при конвертировании

### ISSUE THREAD

**Issue by K-a-R-e-N** [tataranovich/jtv2xmltv#7]
Помогите конвертировать, проблемы не понятные
http://3109117.iptvportal.ru/jtv2.zip

**Comment by tataranovich** [comment]
А какого рода проблема? Падает с ошибкой или неправильно конвертирует?

**Comment by K-a-R-e-N** [comment]
Linux spruthub.local 5.15.79-v7+ #1600 SMP Fri Nov 18 18:20:17 GMT 2022 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jan 17 23:25:56 2024 from 192.168.0.93

pi@spruthub:~ $ git clone https://github.com/tataranovich/jtv2xmltv.git
fatal: destination path 'jtv2xmltv' already exists and is not an empty directory.
pi@spruthub:~ $ cd jtv2xmltv
pi@spruthub:~/jtv2xmltv $ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/test-easy-install-22297.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.9/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

pi@spruthub:~/jtv2xmltv $ wget http://dkt.iptvportal.ru/jtv.zip
--2024-01-23 14:32:22--  http://dkt.iptvportal.ru/jtv.zip
Resolving dkt.iptvportal.ru (dkt.iptvportal.ru)... 82.202.254.188, 185.137.232.12
Connecting to dkt.iptvportal.ru (dkt.iptvportal.ru)|82.202.254.188|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1360508 (1.3M) [application/zip]
Saving to: ‘jtv.zip’

jtv.zip             100%[=================>]   1.30M  2.15MB/s    in 0.6s    

2024-01-23 14:32:23 (2.15 MB/s) - ‘jtv.zip’ saved [1360508/1360508]

pi@spruthub:~/jtv2xmltv $ jtv2xmltv -t +0300 -i jtv.zip -o /tmp/tvguide.xml
Failed to parse 110.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 150.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 160.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 165.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 230.ndx: 'charmap' codec can't decode byte 0x98 in position 24: character maps to <undefined>
Failed to parse 280.ndx: 'charmap' codec can't decode byte 0x98 in position 54: character maps to <undefined>
Failed to parse 300.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 310.ndx: 'charmap' codec can't decode byte 0x98 in position 36: character maps to <undefined>
Failed to parse 410.ndx: 'charmap' codec can't decode byte 0x98 in position 106: character maps to <undefined>
Failed to parse 411.ndx: 'charmap' codec can't decode byte 0x98 in position 11: character maps to <undefined>
Failed to parse 413.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 415.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 510.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 610.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 710.ndx: 'charmap' codec can't decode byte 0x98 in position 11: character maps to <undefined>
Failed to parse 10890.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 10940.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
^CTraceback (most recent call last):
  File "/usr/local/bin/jtv2xmltv", line 33, in <module>
    sys.exit(load_entry_point('jtv2xmltv==0.2.2', 'console_scripts', 'jtv2xmltv')())
  File "/usr/local/lib/python3.9/dist-packages/jtv2xmltv-0.2.2-py3.9.egg/jtv2xmltv/main.py", line 30, in main
    xmltv_content = convert_jtv_to_xmltv(jtv_filename, jtv_encoding=jtv_encoding, xmltv_timezone=tz_format)
  File "/usr/local/lib/python3.9/dist-packages/jtv2xmltv-0.2.2-py3.9.egg/jtv2xmltv/convert.py", line 49, in convert_jtv_to_xmltv
    start=channel_schedules[i]['time'].strftime(time_format),
KeyboardInterrupt

И так дальше идет пока не остановил ctrl+c

**Comment by K-a-R-e-N** [comment]
> А какого рода проблема? Падает с ошибкой или неправильно конвертирует?
`Linux spruthub.local 5.15.79-v7+ #1600 SMP Fri Nov 18 18:20:17 GMT 2022 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.


pi@spruthub:~ $ git clone https://github.com/tataranovich/jtv2xmltv.git
Cloning into 'jtv2xmltv'...
remote: Enumerating objects: 195, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 195 (delta 10), reused 23 (delta 9), pack-reused 165
Receiving objects: 100% (195/195), 557.59 KiB | 1.35 MiB/s, done.
Resolving deltas: 100% (79/79), done.
pi@spruthub:~ $ cd jtv2xmltv
pi@spruthub:~/jtv2xmltv $ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/test-easy-install-22434.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.9/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again. `

**Comment by K-a-R-e-N** [comment]
> А какой-то проблема? Падает с ошибкой или неправильно конвертирует?

Linux spruthub.local 5.15.79-v7+ #1600 SMP Fri Nov 18 18:20:17 GMT 2022 armv7l

pi@spruthub:~ $ git clone https://github.com/tataranovich/jtv2xmltv.git
Cloning into 'jtv2xmltv'...
remote: Enumerating objects: 195, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 195 (delta 10), reused 23 (delta 9), pack-reused 165
Receiving objects: 100% (195/195), 557.59 KiB | 1.35 MiB/s, done.
Resolving deltas: 100% (79/79), done.
pi@spruthub:~ $ cd jtv2xmltv
pi@spruthub:~/jtv2xmltv $ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating jtv2xmltv.egg-info
writing jtv2xmltv.egg-info/PKG-INFO
writing dependency_links to jtv2xmltv.egg-info/dependency_links.txt
writing entry points to jtv2xmltv.egg-info/entry_points.txt
writing top-level names to jtv2xmltv.egg-info/top_level.txt
writing manifest file 'jtv2xmltv.egg-info/SOURCES.txt'
reading manifest file 'jtv2xmltv.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'jtv2xmltv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/tests
copying tests/test_utils.py -> build/lib/tests
copying tests/test_convert.py -> build/lib/tests
copying tests/test_parser.py -> build/lib/tests
copying tests/__init__.py -> build/lib/tests
creating build/lib/jtv2xmltv
copying jtv2xmltv/parser.py -> build/lib/jtv2xmltv
copying jtv2xmltv/utils.py -> build/lib/jtv2xmltv
copying jtv2xmltv/convert.py -> build/lib/jtv2xmltv
copying jtv2xmltv/__init__.py -> build/lib/jtv2xmltv
copying jtv2xmltv/main.py -> build/lib/jtv2xmltv
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/tests
copying build/lib/tests/test_utils.py -> build/bdist.linux-armv7l/egg/tests
copying build/lib/tests/test_convert.py -> build/bdist.linux-armv7l/egg/tests
copying build/lib/tests/test_parser.py -> build/bdist.linux-armv7l/egg/tests
copying build/lib/tests/__init__.py -> build/bdist.linux-armv7l/egg/tests
creating build/bdist.linux-armv7l/egg/jtv2xmltv
copying build/lib/jtv2xmltv/parser.py -> build/bdist.linux-armv7l/egg/jtv2xmltv
copying build/lib/jtv2xmltv/utils.py -> build/bdist.linux-armv7l/egg/jtv2xmltv
copying build/lib/jtv2xmltv/convert.py -> build/bdist.linux-armv7l/egg/jtv2xmltv
copying build/lib/jtv2xmltv/__init__.py -> build/bdist.linux-armv7l/egg/jtv2xmltv
copying build/lib/jtv2xmltv/main.py -> build/bdist.linux-armv7l/egg/jtv2xmltv
byte-compiling build/bdist.linux-armv7l/egg/tests/test_utils.py to test_utils.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/tests/test_convert.py to test_convert.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/tests/test_parser.py to test_parser.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/tests/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/jtv2xmltv/parser.py to parser.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/jtv2xmltv/utils.py to utils.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/jtv2xmltv/convert.py to convert.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/jtv2xmltv/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-armv7l/egg/jtv2xmltv/main.py to main.cpython-39.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying jtv2xmltv.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying jtv2xmltv.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying jtv2xmltv.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying jtv2xmltv.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying jtv2xmltv.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
tests.__pycache__.test_convert.cpython-39: module references __file__
creating dist
creating 'dist/jtv2xmltv-0.2.2-py3.9.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing jtv2xmltv-0.2.2-py3.9.egg
removing '/usr/local/lib/python3.9/dist-packages/jtv2xmltv-0.2.2-py3.9.egg' (and everything under it)
creating /usr/local/lib/python3.9/dist-packages/jtv2xmltv-0.2.2-py3.9.egg
Extracting jtv2xmltv-0.2.2-py3.9.egg to /usr/local/lib/python3.9/dist-packages
jtv2xmltv 0.2.2 is already the active version in easy-install.pth
Installing jtv2xmltv script to /usr/local/bin

Installed /usr/local/lib/python3.9/dist-packages/jtv2xmltv-0.2.2-py3.9.egg
Processing dependencies for jtv2xmltv==0.2.2
Finished processing dependencies for jtv2xmltv==0.2.2
pi@spruthub:~/jtv2xmltv $ wget http://dkt.iptvportal.ru/jtv.zip
--2024-01-23 14:54:37--  http://dkt.iptvportal.ru/jtv.zip
Resolving dkt.iptvportal.ru (dkt.iptvportal.ru)... 82.202.254.188, 185.137.232.12
Connecting to dkt.iptvportal.ru (dkt.iptvportal.ru)|82.202.254.188|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: [1360508](tel:1360508) (1.3M) [application/zip]
Saving to: ‘jtv.zip’

jtv.zip             100%[=================>]   1.30M  2.07MB/s    in 0.6s    

2024-01-23 14:54:38 (2.07 MB/s) - ‘jtv.zip’ saved [1360508/1360508]

pi@spruthub:~/jtv2xmltv $ sudo jtv2xmltv -t +0300 -i jtv.zip -o /tmp/tvguide.xml
Failed to parse 110.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 150.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 160.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 165.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>

Failed to parse 3880.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 3900.ndx: 'charmap' codec can't decode byte 0x98 in position 1: character maps to <undefined>
Failed to parse 3905.ndx: 'charmap' codec can't decode byte 0x98 in position 41: character maps to <undefined>


И без остановки так продолжается пока не надаешь ctrl+c


^CTraceback (most recent call last):
  File "/usr/local/bin/jtv2xmltv", line 33, in <module>
    sys.exit(load_entry_point('jtv2xmltv==0.2.2', 'console_scripts', 'jtv2xmltv')())
  File "/usr/local/lib/python3.9/dist-packages/jtv2xmltv-0.2.2-py3.9.egg/jtv2xmltv/main.py", line 30, in main
    xmltv_content = convert_jtv_to_xmltv(jtv_filename, jtv_encoding=jtv_encoding, xmltv_timezone=tz_format)
  File "/usr/local/lib/python3.9/dist-packages/jtv2xmltv-0.2.2-py3.9.egg/jtv2xmltv/convert.py", line 48, in convert_jtv_to_xmltv
    channel=str(channel_id),
KeyboardInterrupt

**Comment by tataranovich** [comment]
Внутри этого архива кодировка UTF-8. Вот так более-менее сработало у меня:
```
$ jtv2xmltv -i jtv.zip -o jtv.xml -e UTF-8 -t UTC+3
Failed to parse 1807.ndx: unpack requires a buffer of 8 bytes
Failed to parse 2247.ndx: unpack requires a buffer of 8 bytes
Failed to parse 2248.ndx: unpack requires a buffer of 8 bytes
Failed to parse 3361.ndx: unpack requires a buffer of 8 bytes
Failed to parse 3450.ndx: unpack requires a buffer of 8 bytes
Failed to parse 3730.ndx: unpack requires a buffer of 8 bytes
Failed to parse 5428.ndx: unpack requires a buffer of 8 bytes
Failed to parse 12865.ndx: unpack requires a buffer of 8 bytes
```
С ошибками вида `unpack requires a buffer of 8 bytes` нужно разбираться отдельно. Сейчас утилита не умеет декодировать NDX файл если в нём несколько раз сослались на одну и ту же запись в PDT.

**Comment by K-a-R-e-N** [comment]
А как быть? Самы можете как то расшифровать указанный файл http://dkt.iptvportal.ru/jtv.zip

**Comment by K-a-R-e-N** [comment]
Так как? Можете чем то мне помочь ?

**Comment by tataranovich** [comment]
> Так как? Можете чем то мне помочь ?

В ближайшее время я не планирую заниматься этой утилитой, т.к. больше не использую JTV. Попробуйте альтернативные конвертеры или EPG в XMLTV формате.
